DOMAINS = [
    # --- STEM & Hard Sciences ---
    "Quantum Mechanics", "Organic Chemistry", "Marine Biology", "Astrophysics",
    "Number Theory", "Cryptography", "Robotics & Automation", "Neuroscience",
    "Botany and Plant Sciences", "Materials Science", "Fluid Dynamics",
    "Genetics and Genomics", "Meteorology", "Paleontology",
    "Particle Physics", "Cosmology", "Condensed Matter Physics",
    "Thermodynamics", "Electromagnetism", "Optics", "Acoustics",
    "Inorganic Chemistry", "Physical Chemistry", "Analytical Chemistry",
    "Biochemistry", "Molecular Biology", "Cellular Biology",
    "Microbiology", "Virology", "Immunology", "Epidemiology",
    "Entomology", "Ichthyology", "Ornithology", "Herpetology",
    "Mycology", "Phycology", "Taxonomy", "Ecology", "Conservation Biology",
    "Geology", "Mineralogy", "Seismology", "Volcanology",
    "Meteoritics", "Planetary Science", "Climatology", "Oceanography",
    "Glaciology", "Topography", "Cartography", "Crystallography",
    "Polymer Chemistry", "Pharmacology", "Toxicology", "Neuroanatomy",
    "Cognitive Neuroscience", "Behavioral Neuroscience", "Bioinformatics",
    "Computational Biology", "Systems Biology", "Synthetic Biology",
    "Biophysics", "Astrochemistry", "Geochemistry",

    # --- Humanities & Social Sciences ---
    "Medieval European History", "Ancient Mesopotamian Culture", "Post-modern Philosophy",
    "Renaissance Art", "Linguistics & Phonetics", "Classical Mythology",
    "Theology & Comparative Religion", "Macroeconomics", "Cognitive Psychology",
    "Anthropology", "Sociology of the Internet", "Political Science",
    "Ancient Egyptian History", "Feudal Japanese History", "Cold War History",
    "Pre-Columbian Mesoamerican History", "Byzantine Empire", "Dark Ages",
    "Industrial Revolution", "Victorian Era", "Roaring Twenties",
    "Stoicism", "Existentialism", "Nihilism", "Phenomenology",
    "Eastern Philosophy", "Epistemology", "Metaphysics", "Ethics",
    "Aesthetics", "Logic", "Structuralism", "Deconstructionism",
    "Etymology", "Morphology", "Syntax", "Semantics", "Pragmatics",
    "Sociolinguistics", "Historical Linguistics", "Phonology",
    "Behavioral Economics", "Microeconomics", "Game Theory",
    "Austrian Economics", "Keynesian Economics", "Marxist Economics",
    "Developmental Psychology", "Social Psychology", "Clinical Psychology",
    "Evolutionary Psychology", "Forensic Psychology", "Parapsychology",
    "Cultural Anthropology", "Physical Anthropology", "Archaeology",
    "Urban Sociology", "Criminology", "Demography", "Gender Studies",
    "International Relations", "Geopolitics", "Public Policy",
    "Political Economy", "Jurisprudence", "Historiography",

    # --- Tech & Software ---
    "Low-level C Programming", "Distributed Systems Architecture", "Machine Learning",
    "Functional Programming (e.g. Haskell)", "Cybersecurity & Pen Testing",
    "Game Engine Development", "DevOps & CI/CD", "Blockchain & Smart Contracts",
    "Embedded Systems", "WebAssembly", "Database Internals", "UI/UX Design",
    "Operating System Kernels", "Compiler Design", "Reverse Engineering",
    "Malware Analysis", "Binary Exploitation", "Cryptography Engineering",
    "Site Reliability Engineering", "Cloud Architecture", "Container Orchestration",
    "Microservices Architecture", "Event-Driven Architecture", "REST API Design",
    "GraphQL Schema Design", "gRPC & Protocol Buffers", "Wireless Networking",
    "Network Routing Protocols", "Software Defined Networking (SDN)",
    "Computer Vision", "Natural Language Processing", "Reinforcement Learning",
    "Deep Learning", "Generative AI", "Large Language Models (LLMs)",
    "Time Series Forecasting", "Anomaly Detection", "Recommendation Systems",
    "Data Engineering", "ETL Pipelines", "Stream Processing", "Big Data Analytics",
    "FPGA Programming", "ASIC Design", "VLSI Design", "Hardware Description Languages",
    "Internet of Things (IoT)", "Edge Computing", "Fog Computing",
    "AR/VR Development", "Spatial Computing", "Haptics", "Shader Programming",
    "Procedural Generation", "Pathfinding Algorithms", "Collision Detection",
    "Digital Signal Processing", "Image Processing", "Audio Programming",
    "Formal Verification", "Quantum Computing", "Quantum Cryptography",
    "Mainframe Legacy Systems", "Assembly Language", "Real-time Operating Systems (RTOS)",

    # --- Everyday / Hobbies / Practical ---
    "Specialty Coffee Brewing", "Indoor Gardening & Houseplants", "Woodworking",
    "Mechanical Keyboards", "Aquascaping", "Amateur Astronomy", "Baking Science",
    "Automotive Repair", "Home Brewing", "Personal Finance", "Fitness & Kinesiology",
    "Photography & Lighting", "Culinary Techniques", "Interior Design",
    "Lockpicking (Locksport)", "Knife Making", "Blacksmithing", "Leatherworking",
    "Pottery & Ceramics", "Glassblowing", "Origami", "Calligraphy",
    "Scrapbooking", "Cross-Stitching", "Knitting", "Crocheting", "Sewing & Tailoring",
    "Furniture Making", "Carpentry", "Woodcarving", "Pyrography",
    "Bonsai Cultivation", "Ikebana", "Terrarium Building", "Hydroponics",
    "Aquaponics", "Urban Foraging", "Beekeeping", "Chicken Keeping",
    "Vinting & Viticulture", "Cheese Making", "Charcuterie & Curing",
    "Mixology & Bartending", "Sourdough Fermentation", "Kombucha Brewing",
    "Tea Ceremonies", "Mixology", "Cigar Pairing", "Pipe Smoking",
    "Endurance Running", "Powerlifting", "Olympic Weightlifting", "CrossFit",
    "Rock Climbing", "Bouldering", "Mountaineering", "Backpacking",
    "Fly Fishing", "Sport Fishing", "Hunting", "Archery", "Firearms Marksmanship",
    "Sailing & Navigation", "Knot Tying", "Scuba Diving", "Skydiving",
    "Parkour", "Martial Arts", "Self-Defense Tactics", "Yoga", "Pilates",
    "Horology", "Watchmaking", "Sneaker Restoration", "Thrifting & Upcycling",
    "Survival Skills", "Bushcraft", "Prepping & Off-Grid Living",
    "Amateur Radio (Ham Radio)", "Metal Detecting", "Geocaching",
    "Locksmithing", "Home Automation", "Smart Home Integration",
    "Solar Panel Installation", "DIY Electronics", "3D Printing", "CNC Machining",
    "Laser Cutting & Engraving", "Drone Piloting", "Drone Racing",

    # --- Esoteric / Niche / Pop Culture ---
    "Obscure 90s Pop Culture", "Cryptids and Urban Legends", "Speedrunning Video Games",
    "Vintage Watch Restoration", "Constructed Languages (Conlangs)", "TTRPG Worldbuilding",
    "Anime & Manga Tropes", "Board Game Design", "Sci-Fi Literature",
    "Indie Music Scene", "Internet Memes & Lore", "Collectibles & Antiques",
    "ARG (Alternate Reality Games)", "Creepypasta Lore", "Deep Web Lore",
    "Dungeon Synth", "Vaporwave", "Synthwave", "Math Rock", "Shoegaze",
    "Noise Music", "Avant-garde Jazz", "Microgenres", "Lo-fi Hip Hop",
    "Retro Computing", "Demoscene", "Chiptune Music", "CRT Monitors & Retro Gaming",
    "Vintage Console Modding", "Arcade Cabinet Restoration", "Pinball Machine Repair",
    "Furry Fandom", "Otherkin Communities", "Cosplay Armor Making",
    "Historical European Martial Arts (HEMA)", "LARPing", "SCA (Society for Creative Anachronism)",
    "Historical Reenactment", "Steampunk Aesthetics", "Cyberpunk Aesthetics",
    "Dieselpunk", "Solarpunk", "Victorian Goth", "Pastel Goth",
    "Mori Kei", "Lolita Fashion", "Visual Kei", "Streetwear Drops",
    "Sneakerhead Culture", "K-Pop Fandom Dynamics", "Stan Culture",
    "Vtuber Lore", "Twitch Subculture", "YouTube Poops (YTP)",
    "Source Filmmaker (SFM) Animation", "GMOD Machinima", "Roblox Game Development",
    "Minecraft Redstone Engineering", "Minecraft Modding", "ROM Hacking",
    "Speedrun Routing", "Glitch Hunting", "Tool-Assisted Speedruns (TAS)",
    "Competitive Fighting Games (FGC)", "Esports Commentary", "Speedcubing",
    "Competitive Programming", "Code Golfing", "Esoteric Programming Languages",
    "Typewriter Restoration", "Vintage Audio Equipment", "Cassette Tape Culture",
    "Vinyl Record Pressing", "Hi-Fi Audiophile Setup", "Reel-to-Reel Tapes",
    "Puppetry", "Ventriloquism", "Foley Art", "Creature Suit Acting",
    "Miniature Wargaming", "Warhammer 40k Lore", "Tabletop Roleplaying System Design",
    "Zine Culture", "Risograph Printing", "Letterpress Printing", "Bookbinding",

    # --- Arts, Crafts & Performance ---
    "Oil Painting", "Watercolor Painting", "Acrylic Pouring", "Gouache",
    "Charcoal Drawing", "Pastel Drawing", "Digital Illustration", "Pixel Art",
    "Vector Art", "Matte Painting", "Concept Art", "Character Design",
    "Environment Design", "Storyboarding", "Comic Book Inking", "Lettering",
    "Sculpture", "Wire Sculpting", "Ice Carving", "Wood Burning",
    "Mosaic Art", "Stained Glass Art", "Enameling", "Jewelry Making",
    "Metalsmithing", "Engraving", "Printmaking", "Linocut", "Etching",
    "Screen Printing", "Block Printing", "Theater Acting", "Method Acting",
    "Improv Comedy", "Stand-up Comedy", "Stage Magic", "Close-up Magic",
    "Mime", "Pantomime", "Ballet", "Contemporary Dance", "Jazz Dance",
    "Tap Dance", "Ballroom Dance", "Salsa Dancing", "Tango",
    "Hip Hop Dance", "Breakdancing", "Choreography", "Directing",
    "Cinematography", "Film Editing", "Sound Design", "Color Grading",
    "Scriptwriting", "Playwriting", "Poetry", "Creative Nonfiction",
    "Flash Fiction", "Worldbuilding for Fiction", "Costume Design",
    "Set Design", "Lighting Design", "Special Effects Makeup",

    # --- Sports, Games & Recreation ---
    "Chess Theory", "Go Strategy", "Shogi", "Mahjong", "Backgammon",
    "Bridge", "Poker Theory", "Blackjack Card Counting", "Rubik's Cube Solving",
    "Dart Throwing", "Billiards & Snooker", "Foosball", "Table Tennis",
    "Badminton", "Squash", "Tennis", "Pickleball", "Racquetball",
    "Golf Swing Mechanics", "Disc Golf", "Ultimate Frisbee", "Cricket",
    "Baseball Sabermetrics", "Football Tactics", "Basketball Analytics",
    "Hockey Analytics", "Soccer Tiki-Taka", "Rugby Union", "Rugby League",
    "Australian Rules Football", "Gaelic Football", "Hurling", "Curling",
    "Figure Skating", "Speed Skating", "Snowboarding", "Skiing",
    "Surfing", "Windsurfing", "Kiteboarding", "Skateboarding Trick Mechanics",
    "BMX Racing", "Mountain Biking", "Road Cycling", "Velodrome Track Cycling",
    "Formula 1 Aerodynamics", "Rally Racing", "Drag Racing", "Drifting",
    "Motocross", "Enduro Riding", "Horseback Riding (Dressage)", "Show Jumping",
    "Polo", "Fencing", "Kendo", "Brazilian Jiu-Jitsu", "Judo",
    "Muay Thai", "Boxing", "Taekwondo", "Krav Maga", "Sumo Wrestling",

    # --- Business, Law & Finance ---
    "Corporate Law", "Antitrust Law", "Intellectual Property Law",
    "Patent Law", "Copyright Law", "Trademark Law", "International Law",
    "Maritime Law", "Space Law", "Environmental Law", "Tax Law",
    "Constitutional Law", "Criminal Law", "Civil Litigation",
    "Mergers & Acquisitions", "Venture Capital", "Private Equity",
    "Investment Banking", "Hedge Fund Strategies", "Algorithmic Trading",
    "Day Trading", "Options Trading", "Forex Trading", "Commodity Trading",
    "Real Estate Investment Trusts (REITs)", "Property Management",
    "Corporate Accounting", "Forensic Accounting", "Auditing",
    "Supply Chain Logistics", "Operations Management", "Six Sigma",
    "Agile Project Management", "Scrum Mastery", "Product Management",
    "Growth Hacking", "Search Engine Optimization (SEO)", "Digital Marketing",
    "Affiliate Marketing", "Behavioral Marketing", "Neuromarketing",
    "Actuarial Science", "Risk Management", "Underwriting", "Insurance Claims",
    "Human Resources", "Organizational Behavior", "Labor Relations",
    "Business Intelligence", "Data Visualization", "Enterprise Architecture",
    "Customer Success Management", "B2B Sales", "Negotiation Tactics",
    "Public Relations", "Crisis Management", "Brand Identity Design",
    "Franchise Management", "E-commerce Logistics", "Dropshipping",

    # --- Transportation & Engineering ---
    "Aerospace Engineering", "Aeronautics", "Astronautics",
    "Propulsion Systems", "Avionics", "Air Traffic Control",
    "Naval Architecture", "Marine Engineering", "Submarine Design",
    "Civil Engineering", "Structural Engineering", "Geotechnical Engineering",
    "Transportation Engineering", "Traffic Flow Theory", "Highway Engineering",
    "Bridge Design", "Dam Construction", "Tunnel Boring",
    "Mechanical Engineering", "Thermodynamics", "HVAC Systems Design",
    "Manufacturing Engineering", "Industrial Engineering",
    "Automation Engineering", "Control Systems Engineering",
    "Robotics Kinematics", "Pneumatics", "Hydraulics",
    "Electrical Engineering", "Power Electronics", "Control Systems",
    "Power Grid Distribution", "Renewable Energy Systems", "Solar Power Tech",
    "Wind Turbine Aerodynamics", "Hydroelectric Power", "Nuclear Power Plant Design",
    "Battery Technology", "Fuel Cells", "Electric Vehicle Drivetrains",
    "Internal Combustion Engine Design", "Transmission Systems",
    "Automotive Aerodynamics", "Suspension Dynamics", "Tire Compounding",
    "Locomotive Engineering", "Railway Signaling", "Maglev Technology",
    "Hyperloop Propulsion", "Bicycle Frame Geometry", "Motorcycle Chassis Dynamics",
    "Urban Transit Planning", "Logistics Routing", "Port Operations",

    # --- Medicine & Health ---
    "Radiology", "Pathology", "Dermatology", "Cardiology", "Neurology",
    "Gastroenterology", "Endocrinology", "Nephrology", "Pulmonology",
    "Rheumatology", "Oncology", "Hematology", "Infectious Diseases",
    "Sports Medicine", "Orthopedic Surgery", "Neurosurgery",
    "Cardiothoracic Surgery", "Plastic Surgery", "General Surgery",
    "Pediatrics", "Geriatrics", "Obstetrics", "Gynecology",
    "Neonatology", "Perinatology", "Psychiatry", "Anesthesiology",
    "Emergency Medicine", "Critical Care Medicine", "Toxicology",
    "Dermatopathology", "Forensic Pathology", "Veterinary Medicine",
    "Equine Medicine", "Feline Internal Medicine", "Zoological Medicine",
    "Physical Therapy", "Occupational Therapy", "Speech-Language Pathology",
    "Audiology", "Optometry", "Dentistry", "Orthodontics",
    "Endodontics", "Periodontics", "Prosthodontics", "Oral Surgery",
    "Nutrition & Dietetics", "Bariatric Medicine", "Diabetes Management",
    "Integrative Medicine", "Osteopathic Medicine", "Chiropractic Care",
    "Acupuncture", "Physical Rehabilitation", "Prosthetics Design",
    "Orthotics Design", "Medical Device Engineering", "Biomedical Imaging",
    "Surgical Robotics", "Telemedicine Platforms", "Electronic Health Records (EHR)",
    "Pharmacogenomics", "Clinical Trials Design", "Epidemiological Modeling"
]